import assert from "node:assert/strict";
import test from "node:test";
import { collectConversationAssetReferences, collectProjectAssetReferences, mergeAssetInventory } from "../apps/extension/src/asset-inventory.js";

test("collects uploaded images, attachments and sandbox outputs without losing references", () => {
  const raw={id:"c1",mapping:{user:{message:{id:"m1",author:{role:"user"},content:{content_type:"multimodal_text",parts:[{content_type:"image_asset_pointer",asset_pointer:"sediment://file_image123456",size_bytes:12,metadata:{dalle:{}}},{asset_pointer:"sediment://file_image123456"}]},metadata:{attachments:[{file_id:"file_doc123456",name:"paper.pdf",mime_type:"application/pdf",size_bytes:20}]}}},tool:{message:{id:"m2",author:{role:"tool"},content:{content_type:"text",parts:["[result](sandbox:/mnt/data/result.csv)"]},metadata:{}}}}};
  const assets=collectConversationAssetReferences(raw,{id:"c1",locations:[]});
  assert.equal(assets.length,3);const image=assets.find((item)=>item.fileId==="file_image123456");assert.equal(image.kind,"dalle-image");assert.equal(image.expectedBytes,12);assert.ok(image.references.length>=2);const pdf=assets.find((item)=>item.fileId==="file_doc123456");assert.equal(pdf.fileName,"paper.pdf");assert.equal(pdf.mimeType,"application/pdf");const sandbox=assets.find((item)=>item.sandboxPath);assert.equal(sandbox.downloadable,false);assert.equal(sandbox.kind,"code-output");
});

test("deduplicates the same fileId across conversations and project files",()=>{const conversation=collectConversationAssetReferences({id:"c1",mapping:{n:{message:{id:"m",author:{role:"user"},content:{parts:[{asset_pointer:"sediment://file_shared123"}]},metadata:{}}}}},{id:"c1",locations:[]});const project=collectProjectAssetReferences([{id:"g-p-1",title:"Alpha",files:[{file_id:"file_shared123",name:"shared.png",type:"image/png"}]}]);const merged=mergeAssetInventory(conversation,project);assert.equal(merged.length,1);assert.deepEqual(merged[0].conversationIds,["c1"]);assert.deepEqual(merged[0].projectIds,["g-p-1"]);assert.equal(merged[0].fileName,"shared.png");});

test("preserves Chinese sandbox filenames and classifies Project catalog files separately",()=>{const assets=collectConversationAssetReferences({id:"c-project",mapping:{user:{message:{id:"m-user",author:{role:"user"},content:{parts:[{content_type:"image_asset_pointer",asset_pointer:"sediment://file_project_image123",mime_type:"image/png",file_name:"截图.png"},"[结果](sandbox:/mnt/data/分析 结果.csv)"]},metadata:{}}}}},{id:"c-project",locations:[{type:"project",projectId:"g-p-1",projectTitle:"Alpha",present:true}]});assert.equal(assets.find((item)=>item.fileId).kind,"user-image");assert.equal(assets.find((item)=>item.sandboxPath).fileName,"分析 结果.csv");const projectFile=collectProjectAssetReferences([{id:"g-p-1",title:"Alpha",files:[{file_id:"file_project_doc123",name:"资料.pdf",type:"application/pdf"}]}])[0];assert.equal(projectFile.kind,"project-file");});
